"""Copyright 2024 - 2025 The excelize Authors. All rights reserved. Use of this
source code is governed by a BSD-style license that can be found in the LICENSE
file.

Package excelize-py is a Python port of Go Excelize library, providing a set of
functions that allow you to write and read from XLAM / XLSM / XLSX / XLTM / XLTX
files. Supports reading and writing spreadsheet documents generated by Microsoft
Excel™ 2007 and later. Supports complex components by high compatibility, and
provided streaming API for generating or reading data from a worksheet with huge
amounts of data. This library needs Python version 3.9 or later.
"""

from __future__ import annotations
import sys
from warnings import warn
import os
import shutil
from setuptools import setup
from setuptools.command.install import install

if sys.version_info < (3, 9):
    warn("The minimum Python version supported by excelize is 3.9")
    exit()


class CustomInstallCommand(install):
    def run(self):
        install.run(self)
        os.makedirs(self.install_lib, exist_ok=True)
        for shared_library in [
            "libexcelize.386.linux.so",
            "libexcelize.amd64.linux.so",
            "libexcelize.arm64.linux.so",
            "libexcelize.amd64.darwin.dylib",
            "libexcelize.arm64.darwin.dylib",
            "libexcelize.386.windows.dll",
            "libexcelize.amd64.windows.dll",
            "libexcelize.arm64.windows.dll",
        ]:
            shutil.copy(shared_library, self.install_lib)


setup(
    name="excelize",
    version="0.0.8",
    license="BSD 3-Clause",
    license_files=("LICENSE"),
    description="A Python build of the Go Excelize library for reading and writing Microsoft Excel™ (XLAM / XLSM / XLSX / XLTM / XLTX) spreadsheets",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="xuri",
    author_email="xuri.me@gmail.com",
    maintainer="xuri",
    maintainer_email="xuri.me@gmail.com",
    zip_safe=False,
    url="https://github.com/xuri/excelize-py",
    project_urls={
        "Source": "https://github.com/xuri/excelize-py",
        "Documentation": "https://xuri.me/excelize-py",
        "Issue Tracker": "https://github.com/xuri/excelize-py/issues",
        "Changelog": "https://github.com/xuri/excelize-py/releases",
        "Funding": "https://github.com/sponsors/xuri",
        "Discord": "https://discord.com/invite/MWV8MBQGtv",
        "Gitter": "https://gitter.im/excelize/community",
        "Reddit": "https://www.reddit.com/r/excelize/",
        "Slack": "https://join.slack.com/t/xuri/shared_invite/zt-eriqdkeo-wV04zcCdBiiZveFgY86Wzw",
        "Mastodon": "https://mastodon.social/@xurime",
        "Twitter": "https://x.com/xurime",
        "Youtube": "https://www.youtube.com/@rixu",
    },
    cmdclass={"install": CustomInstallCommand},
    py_modules=[
        "excelize",
        "types_go",
        "types_py",
    ],
    python_requires=">=3.9",
    keywords=[
        "excelize",
        "excel",
        "xlsx",
        "xlsm",
        "xltx",
        "xltm",
        "xls",
        "spreadsheet",
        "workbook",
        "vba",
        "macro",
    ],
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "License :: OSI Approved :: BSD License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3 :: Only",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
        "Programming Language :: Python :: 3.15",
    ],
)
